/**
 * Tier 4 — Structural Fidelity Expansion (8 new fixtures)
 *
 * Deep structural complexity that stresses compressor nesting:
 *   1. Deep DOM tree (20+ levels)
 *   2. Multi-window OSWorld state
 *   3. Multi-table GAIA reasoning input
 *   4. Multi-file SWE-verified patch
 *   5. DOM with dynamic attributes
 *   6. HTML with embedded JSON and XML
 *   7. OSWorld with symlink loops in file tree
 *   8. GAIA-style multi-step reasoning input
 */
import type { ChallengeFixture } from "../types"

function deepDiv(depth: number, current: number = 0): string {
  const indent = "  ".repeat(current)
  if (current >= depth) return `${indent}<span class="leaf">Content at depth ${current}</span>`
  return `${indent}<div class="level-${current}" id="node-${current}">\n${deepDiv(depth, current + 1)}\n${indent}</div>`
}

export const TIER4_STRUCTURAL_EXPANSION_FIXTURES: readonly ChallengeFixture[] = [
  // 1. Deep DOM tree (25 levels)
  {
    id: "struct-t4-01",
    tier: 4,
    category: "webarena-style",
    description: "Deep nested DOM tree with 25 levels of nesting",
    seed: 40001,
    input: {
      content: `<!DOCTYPE html>\n<html>\n<body>\n${deepDiv(25)}\n</body>\n</html>`,
      tool: "bash",
      command: "cat page.html",
    },
    expected: {
      type: "objective",
      mustContain: ["level-0", "level-12", "level-24", "Content at depth 25"],
      workflow: "swe",
    },
  },

  // 2. Multi-window OSWorld state
  {
    id: "struct-t4-02",
    tier: 4,
    category: "osworld-style",
    description: "Multi-window desktop state with clipboard, processes, and file tree",
    seed: 40002,
    input: {
      content: [
        `=== Window 1: VS Code (focused) ===`,
        `File: /project/src/index.ts`,
        `Line 42, Column 15`,
        `Language: TypeScript`,
        `Encoding: UTF-8`,
        `EOL: LF`,
        `Tabs: 2 spaces`,
        ``,
        `=== Window 2: Terminal ===`,
        `$ bun run dev`,
        `Server running on http://localhost:3000`,
        `[HMR] Connected`,
        ``,
        `=== Window 3: Chrome DevTools ===`,
        `Console:`,
        `  [info] App initialized`,
        `  [warn] Deprecated API: window.localStorage.getItem('legacy_key')`,
        `Network:`,
        `  GET /api/users 200 45ms`,
        `  GET /api/config 200 12ms`,
        `  WS  /ws/updates  Connected`,
        ``,
        `=== Clipboard ===`,
        `const handleSubmit = async (data: FormData) => {`,
        `  const response = await api.post('/submit', data);`,
        `  return response.json();`,
        `};`,
        ``,
        `=== File Explorer ===`,
        `project/`,
        `├── src/`,
        `│   ├── index.ts`,
        `│   ├── components/`,
        `│   │   ├── App.tsx`,
        `│   │   ├── Header.tsx`,
        `│   │   └── Footer.tsx`,
        `│   └── lib/`,
        `│       ├── api.ts`,
        `│       └── utils.ts`,
        `├── test/`,
        `│   └── app.test.ts`,
        `├── package.json`,
        `└── tsconfig.json`,
        ``,
        `=== Process List (top 5 by CPU) ===`,
        `PID    CPU%  MEM%  COMMAND`,
        `1234   12.3  4.5   bun run dev`,
        `5678    8.1  15.2  chrome --type=renderer`,
        `9012    3.4   2.1  code --extensionDevelopmentPath`,
        `3456    1.2   0.8  typescript-language-server`,
        `7890    0.5   0.3  eslint_d`,
      ].join("\n"),
      tool: "bash",
      command: "osworld-state",
    },
    expected: {
      type: "objective",
      mustContain: ["VS Code (focused)", "Clipboard", "handleSubmit", "bun run dev"],
      workflow: "swe",
    },
  },

  // 3. Multi-table GAIA reasoning
  {
    id: "struct-t4-03",
    tier: 4,
    category: "gaia-style",
    description: "GAIA-style task with tables, logs, JSON, and instructions",
    seed: 40003,
    input: {
      content: [
        `Task: Determine the root cause of the latency spike on 2026-09-20.`,
        ``,
        `=== Latency Data (p99, ms) ===`,
        `| Time       | API  | DB   | Cache | Total |`,
        `|------------|------|------|-------|-------|`,
        `| 10:00      | 12   | 8    | 2     | 22    |`,
        `| 10:15      | 15   | 12   | 2     | 29    |`,
        `| 10:30      | 45   | 120  | 2     | 167   |`,
        `| 10:45      | 52   | 185  | 3     | 240   |`,
        `| 11:00      | 18   | 15   | 2     | 35    |`,
        ``,
        `=== Database Slow Queries ===`,
        `{"timestamp":"10:28","query":"SELECT * FROM orders WHERE status='pending' ORDER BY created_at","duration_ms":1250,"rows_scanned":450000}`,
        `{"timestamp":"10:32","query":"UPDATE inventory SET quantity=quantity-1 WHERE product_id IN (SELECT product_id FROM cart_items WHERE cart_id='abc123')","duration_ms":2100,"rows_scanned":890000}`,
        ``,
        `=== Server Logs ===`,
        `10:25:00 INFO  Autoscaler: scaling up from 2 to 4 replicas`,
        `10:28:15 WARN  Connection pool exhausted (max: 20, active: 20, waiting: 15)`,
        `10:30:00 ERROR Query timeout after 5000ms: SELECT * FROM orders...`,
        `10:45:00 INFO  Connection pool recovered (active: 8, waiting: 0)`,
        `10:55:00 INFO  Autoscaler: scaling down from 4 to 2 replicas`,
        ``,
        `Instructions: Analyze the data above and identify which component caused the spike.`,
      ].join("\n"),
      tool: "bash",
      command: "cat incident-report.txt",
    },
    expected: {
      type: "objective",
      mustContain: ["Latency Data", "Connection pool exhausted", "orders", "duration_ms"],
      workflow: "swe",
    },
  },

  // 4. Multi-file SWE-verified patch
  {
    id: "struct-t4-04",
    tier: 4,
    category: "swe-bench-verified",
    description: "Multi-patch SWE issue: failing → first fix → second fix → verified",
    seed: 40004,
    input: {
      content: [
        `Issue #4521: FormValidator.validate() throws on nested objects`,
        ``,
        `Failing test:`,
        `  validator.validate({ user: { name: "Kim", address: { city: "NYC" } } })`,
        `  Expected: { valid: true, errors: [] }`,
        `  Received: TypeError: Cannot read properties of undefined (reading 'rules')`,
        ``,
        `=== Patch 1 (partial fix) ===`,
        `diff --git a/src/validator.ts b/src/validator.ts`,
        `--- a/src/validator.ts`,
        `+++ b/src/validator.ts`,
        `@@ -45,3 +45,7 @@`,
        `   validate(data: Record<string, unknown>): ValidationResult {`,
        `-    return this.checkRules(data);`,
        `+    return this.checkRules(data, this.schema);`,
        `+  }`,
        `+`,
        `+  private checkRules(data: unknown, schema: Schema): ValidationResult {`,
        `+    if (typeof data === 'object' && data !== null) {`,
        `+      return this.validateObject(data as Record<string, unknown>, schema);`,
        ``,
        `Result after patch 1: Still failing — validateObject doesn't recurse`,
        ``,
        `=== Patch 2 (complete fix) ===`,
        `diff --git a/src/validator.ts b/src/validator.ts`,
        `--- a/src/validator.ts`,
        `+++ b/src/validator.ts`,
        `@@ -60,4 +60,10 @@`,
        `   private validateObject(data: Record<string, unknown>, schema: Schema): ValidationResult {`,
        `     const errors: string[] = [];`,
        `     for (const [key, value] of Object.entries(data)) {`,
        `-      if (!this.checkField(key, value, schema[key])) {`,
        `+      const fieldSchema = schema[key];`,
        `+      if (fieldSchema?.type === 'object' && typeof value === 'object') {`,
        `+        const nested = this.validateObject(value as Record<string, unknown>, fieldSchema.properties);`,
        `+        errors.push(...nested.errors);`,
        `+      } else if (!this.checkField(key, value, fieldSchema)) {`,
        `         errors.push(\`Invalid: \${key}\`);`,
        ``,
        `Final test result: PASS`,
        `  validator.validate({ user: { name: "Kim", address: { city: "NYC" } } })`,
        `  Result: { valid: true, errors: [] }`,
      ].join("\n"),
      tool: "bash",
      command: "cat issue-4521-resolution.txt",
    },
    expected: {
      type: "objective",
      mustContain: ["FormValidator", "nested objects", "validateObject", "PASS"],
      workflow: "swe",
    },
  },

  // 5. DOM with dynamic attributes
  {
    id: "struct-t4-05",
    tier: 4,
    category: "webarena-style",
    description: "DOM elements with aria-*, data-*, and event handler attributes",
    seed: 40005,
    input: {
      content: [
        `<div id="app-root" data-testid="main-app" data-version="2.1.0">`,
        `  <nav role="navigation" aria-label="Main navigation" data-collapsed="false">`,
        `    <ul role="menubar" aria-orientation="horizontal">`,
        `      <li role="menuitem" aria-current="page" data-route="/dashboard">`,
        `        <a href="/dashboard" tabindex="0" aria-describedby="nav-tip-1">Dashboard</a>`,
        `      </li>`,
        `      <li role="menuitem" data-route="/settings" aria-haspopup="true">`,
        `        <a href="/settings" tabindex="-1">Settings</a>`,
        `        <ul role="menu" aria-label="Settings submenu" data-depth="1">`,
        `          <li role="menuitem" data-route="/settings/profile">Profile</li>`,
        `          <li role="menuitem" data-route="/settings/security">Security</li>`,
        `        </ul>`,
        `      </li>`,
        `    </ul>`,
        `  </nav>`,
        `  <main role="main" aria-live="polite" data-loading="false">`,
        `    <div class="dashboard-grid" data-columns="3" data-gap="16px">`,
        `      <div class="widget" data-widget-id="stats" data-refresh-interval="30000"`,
        `           aria-label="Statistics widget" role="region">`,
        `        <h2 id="stats-heading">Statistics</h2>`,
        `        <div aria-describedby="stats-heading" data-chart-type="bar">`,
        `          <canvas data-rendered="true" width="400" height="300"></canvas>`,
        `        </div>`,
        `      </div>`,
        `    </div>`,
        `  </main>`,
        `</div>`,
      ].join("\n"),
      tool: "bash",
      command: "cat dom-snapshot.html",
    },
    expected: {
      type: "objective",
      mustContain: ["aria-label", "data-testid", "aria-current=\"page\"", "data-widget-id"],
      workflow: "swe",
    },
  },

  // 6. HTML with embedded JSON and XML
  {
    id: "struct-t4-06",
    tier: 4,
    category: "webarena-style",
    description: "HTML page with embedded JSON-LD, SVG (XML), and inline JSON",
    seed: 40006,
    input: {
      content: [
        `<!DOCTYPE html>`,
        `<html>`,
        `<head>`,
        `  <script type="application/ld+json">`,
        `  {`,
        `    "@context": "https://schema.org",`,
        `    "@type": "Organization",`,
        `    "name": "Acme Corp",`,
        `    "url": "https://acme.example.com",`,
        `    "contactPoint": {`,
        `      "@type": "ContactPoint",`,
        `      "telephone": "+1-555-0100",`,
        `      "contactType": "customer service"`,
        `    }`,
        `  }`,
        `  </script>`,
        `</head>`,
        `<body>`,
        `  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">`,
        `    <circle cx="50" cy="50" r="40" fill="none" stroke="#333" stroke-width="2"/>`,
        `    <text x="50" y="55" text-anchor="middle" font-size="14">Logo</text>`,
        `  </svg>`,
        `  <div id="config" data-config='{"api":"https://api.acme.com","version":"2.1"}'></div>`,
        `  <script>`,
        `    const config = JSON.parse(document.getElementById('config').dataset.config);`,
        `    fetch(config.api + '/health').then(r => r.json()).then(console.log);`,
        `  </script>`,
        `</body>`,
        `</html>`,
      ].join("\n"),
      tool: "bash",
      command: "cat index.html",
    },
    expected: {
      type: "objective",
      mustContain: ["application/ld+json", "schema.org", "xmlns", "data-config"],
      workflow: "swe",
    },
  },

  // 7. File tree with symlink loops
  {
    id: "struct-t4-07",
    tier: 4,
    category: "osworld-style",
    description: "File tree with circular symlinks and deep nesting",
    seed: 40007,
    input: {
      content: [
        `$ find /project -maxdepth 8 -type l -o -type f -o -type d | head -60`,
        `/project`,
        `/project/src`,
        `/project/src/index.ts`,
        `/project/src/lib`,
        `/project/src/lib/utils.ts`,
        `/project/src/lib/types.ts`,
        `/project/node_modules`,
        `/project/node_modules/.package-lock.json`,
        `/project/node_modules/express`,
        `/project/node_modules/express/lib`,
        `/project/node_modules/express/lib/router`,
        `/project/node_modules/express/lib/router/index.js`,
        `/project/vendor`,
        `/project/vendor/lib -> ../src/lib`,
        `/project/vendor/circular -> ../vendor`,
        `/project/vendor/deep`,
        `/project/vendor/deep/level1`,
        `/project/vendor/deep/level1/level2`,
        `/project/vendor/deep/level1/level2/level3`,
        `/project/vendor/deep/level1/level2/level3/back -> ../../../../vendor`,
        ``,
        `$ ls -la /project/vendor/`,
        `total 8`,
        `drwxr-xr-x 4 user user 128 Sep 22 10:00 .`,
        `drwxr-xr-x 6 user user 192 Sep 22 10:00 ..`,
        `lrwxrwxrwx 1 user user  10 Sep 22 10:00 lib -> ../src/lib`,
        `lrwxrwxrwx 1 user user   9 Sep 22 10:00 circular -> ../vendor`,
        `drwxr-xr-x 3 user user  96 Sep 22 10:00 deep`,
        ``,
        `$ readlink -f /project/vendor/circular`,
        `/project/vendor`,
        ``,
        `$ file /project/vendor/lib/utils.ts`,
        `/project/vendor/lib/utils.ts: ASCII text, with UTF-8 Unicode characters`,
      ].join("\n"),
      tool: "bash",
      command: "find /project",
    },
    expected: {
      type: "objective",
      mustContain: ["lib -> ../src/lib", "circular -> ../vendor", "back -> ../../../../vendor", "readlink"],
      workflow: "swe",
    },
  },

  // 8. GAIA multi-step reasoning input
  {
    id: "struct-t4-08",
    tier: 4,
    category: "gaia-style",
    description: "GAIA-style task with chain-of-thought reasoning input",
    seed: 40008,
    input: {
      content: [
        `Task: Given the server metrics below, predict whether the system will need scaling in the next hour.`,
        ``,
        `=== Current Metrics ===`,
        `CPU: 72% (trending up from 45% 30 min ago)`,
        `Memory: 6.2 GB / 8 GB (77.5%)`,
        `Disk I/O: 450 IOPS (limit: 1000)`,
        `Network: 120 Mbps in, 85 Mbps out (limit: 1 Gbps)`,
        `Active connections: 2,450 (limit: 5,000)`,
        `Request queue depth: 127 (target: < 50)`,
        ``,
        `=== Historical Pattern (last 7 days, same hour) ===`,
        `| Day | CPU Peak | Memory Peak | Connections | Scale Event? |`,
        `|-----|----------|-------------|-------------|--------------|`,
        `| Mon | 65%      | 5.8 GB      | 1,800       | No           |`,
        `| Tue | 71%      | 6.0 GB      | 2,100       | No           |`,
        `| Wed | 78%      | 6.5 GB      | 2,800       | Yes (manual) |`,
        `| Thu | 82%      | 7.1 GB      | 3,200       | Yes (auto)   |`,
        `| Fri | 60%      | 5.2 GB      | 1,500       | No           |`,
        `| Sat | 42%      | 4.1 GB      | 900         | No           |`,
        `| Sun | 38%      | 3.8 GB      | 750         | No           |`,
        ``,
        `=== Autoscaler Config ===`,
        `{`,
        `  "target_cpu": 70,`,
        `  "target_memory_pct": 80,`,
        `  "scale_up_threshold": 75,`,
        `  "scale_down_threshold": 40,`,
        `  "cooldown_period_seconds": 300,`,
        `  "min_replicas": 2,`,
        `  "max_replicas": 8,`,
        `  "current_replicas": 3`,
        `}`,
        ``,
        `Reasoning steps:`,
        `1. Current CPU (72%) is above target (70%) and trending up`,
        `2. Memory (77.5%) is approaching threshold (80%)`,
        `3. Request queue (127) is 2.5x the target (50)`,
        `4. Historical pattern shows Wed/Thu at similar levels triggered scaling`,
        `5. Today is Monday — lower historical baseline but current load exceeds pattern`,
        ``,
        `Prediction: Scale-up likely within 15 minutes based on CPU trend and queue depth.`,
      ].join("\n"),
      tool: "bash",
      command: "cat analysis.txt",
    },
    expected: {
      type: "objective",
      mustContain: ["scale_up_threshold", "Request queue depth", "Historical Pattern", "Prediction"],
      workflow: "swe",
    },
  },
]
